[application]
name = "mir-music"
version = "0.0.0"
authors = ["Michael Li <alimy@gility.net>"]
description = "music infomation service"
license = "Apache-2.0"

[serve]
schema = "http"
addr = "127.0.0.1"
port = 8013
certFile = "cert.pem"
keyFile = "key.pem"

[database]
# Ether "mysql", "postgres" or "sqlite3", you can connect to TiDB with MySQL protocol
type = "mysql"
host = "127.0.0.1:3306"
name = "media"
user = "root"
passwd = ""
param = ""
# For "postgres" only, either "disable", "require" or "verify-full"
sslMode = "disable"
# For "sqlite3" and "tidb", use absolute path when you start as service
path = ":memory:"

[redis]
network = "tcp"
addr = "127.0.0.1:6379"